# Generated by Django 3.1.4 on 2021-02-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='postal_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
