"""
Django settings for grph project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '+j62t^__5z4qml9&3t3mn9b&n2)9wt-j1ha73vvz6)c#bmgo=9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    # 'material.admin',
    # 'material.admin.default',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "graphene_django",
    "django_filters",
    "posts",
    "categories",
    'rest_framework',
    "accounts",
    "regions"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
]

ROOT_URLCONF = 'grph.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'grph.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


AUTHENTICATION_BACKENDS = [
    'graphql_jwt.backends.JSONWebTokenBackend',
    'django.contrib.auth.backends.ModelBackend',
]


GRAPHENE = {
    "SCHEMA": "grph.schema.schema",
    'MIDDLEWARE': [
        'graphql_jwt.middleware.JSONWebTokenMiddleware',
    ]
}



JAZZMIN_SETTINGS = {
    "site_title": "Library Admin",
    "site_header": "Administration",
    "hide_apps": ['rest_framework.authtoken'],
    "custom_links": {
        "posts": [{
            "name": "Ajouter entreprise",
            "url": "/admin/posts/post/add/",
            "icon": "fas fa-plus",
            # "permissions": ["books.view_book"]
        }],
        "pub":[{
            "name":"Ajouter pub",
            "url":"/admin/pub/pub/add/",
            "icon":"fas fa-plus"
        }],
        "abonements":[{
            "name":"Ajouter abonné",
            "url":"/admin/abonements/abonne/add/",
            "icon":"fas fa-plus"
        }],
        "partenariat":[{
            "name":"Ajouter partenaire",
            "url":"/admin/partenariat/partenaire/add/",
            "icon":"fas fa-plus"
        }]
    },
    "icons": {
        "categories.category": "fas fa-clipboard-list",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "posts.Post": "fas fa-industry",
        # "posts.Activity": "fab fa-buffer",
        "regions.Region":"fa fa-globe",
        "regions.Country":"fa fa-globe",
        "regions.City":"fa fa-globe",
        "pub.Pub":"far fa-images",
        # "pub.PubType":"far fa-square",
        # "abonements.Abonement":"fas fa-history",
        # "abonements.Abonne":"fas fa-user-clock",
        # "abonements.TypeAbonement":"far fa-clock",
        # "partenariat.Partenaire":"fas fa-user-clock",
        # "contact.Contact":"fa fa-envelope",
        # "newsletter.Newsletter":"far fa-newspaper",
    },
    "copyright": "Something cool",
}


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
